import { useConfig } from '@/store/configStore';

export function PurchaseDocument({order}:{order:any}) {
 const {company,logoValue}=useConfig();const addr=order.billing_address||order.shipping_address||{};const shipping=order.shipping_address||{};
 const money=(n:number)=>new Intl.NumberFormat('es-PE',{style:'currency',currency:order.currency||'PEN'}).format(Number(n)||0);
 return <article id="purchase-document" className="purchase-document">
  <header><div>{logoValue&&<img src={logoValue} alt={company.company_name||'Logo de la empresa'} onError={e=>{e.currentTarget.style.display='none'}}/>}<h1>{company.company_name||'Empresa: pendiente de configurar'}</h1><p>RUC: {company.company_ruc||'Pendiente de configurar'}</p><p>{company.company_address}</p><p>{[company.company_phone,company.company_email].filter(Boolean).join(' · ')}</p></div><div className="document-number"><strong>COMPROBANTE DE COMPRA</strong><p>{order.order_number}</p><p>{new Date(order.created_at).toLocaleDateString('es-PE',{timeZone:'America/Lima'})}</p><p>{order.payment_status==='paid'?'PAGO CONFIRMADO':'PAGO PENDIENTE'}</p></div></header>
  <section className="document-customer"><h2>Datos del cliente</h2><p><b>Cliente:</b> {addr.razon_social||addr.full_name||shipping.full_name||'No registrado'}</p><p><b>Documento:</b> {addr.ruc?'RUC '+addr.ruc:addr.dni?'DNI '+addr.dni:'No registrado'}</p><p><b>Dirección:</b> {[addr.address||shipping.address,shipping.district,shipping.city,shipping.region].filter(Boolean).join(', ')}</p></section>
  <table><thead><tr><th>Descripción</th><th>Cant.</th><th>Precio unitario</th><th>Importe</th></tr></thead><tbody>{(order.items||[]).map((item:any)=><tr key={item.id}><td><b>{item.product_name}</b>{item.variant_name&&<p>{item.variant_name}</p>}{item.sku&&<small>SKU: {item.sku}</small>}</td><td>{item.quantity}</td><td>{money(item.unit_price)}</td><td>{money(item.total)}</td></tr>)}</tbody></table>
  <section className="document-totals"><p><span>Subtotal registrado</span><b>{money(order.subtotal)}</b></p>{Number(order.discount_amount)>0&&<p><span>Descuento</span><b>−{money(order.discount_amount)}</b></p>}<p><span>Envío</span><b>{money(order.shipping_amount)}</b></p><p><span>{Math.abs(Number(order.total)-(Number(order.subtotal)-Number(order.discount_amount||0)+Number(order.shipping_amount||0)))<0.02?'Impuesto incluido':'Impuesto'}</span><b>{money(order.tax_amount)}</b></p><p className="document-total"><span>Total pagadero · {order.currency}</span><b>{money(order.total)}</b></p></section>
  <section><h2>Información de pago y entrega</h2><p>Método: {order.payment_method||'No registrado'}</p>{order.payment_reference&&<p>Referencia: {order.payment_reference}</p>}<p>Entrega: {order.shipping_method_name||'No registrada'}</p>{order.tracking_number&&<p>Seguimiento: {order.tracking_number}</p>}</section>
  <footer><strong>Gracias por confiar en {company.company_name||'nosotros'}</strong><p>Consulta el seguimiento y tu comprobante en Mis pedidos.</p><p>{[company.company_email,company.company_phone].filter(Boolean).join(' · ')}</p></footer>
  <style>{`.purchase-document{background:white;color:#17202a;padding:32px;font:13px/1.5 Arial,sans-serif;max-width:800px;margin:auto;border:1px solid #dce0e5;border-radius:12px}.purchase-document header{display:flex;justify-content:space-between;gap:24px;border-bottom:2px solid #17202a;padding-bottom:20px}.purchase-document header img{max-width:160px;max-height:64px;object-fit:contain;margin-bottom:12px}.purchase-document h1{font-size:18px;font-weight:700}.purchase-document h2{font-size:13px;font-weight:700;margin-bottom:8px}.purchase-document section{padding:18px 0}.purchase-document .document-number{text-align:right;min-width:190px}.purchase-document table{width:100%;border-collapse:collapse}.purchase-document th{text-align:left;background:#f1f3f5;font-size:11px}.purchase-document th,.purchase-document td{padding:10px 8px;border-bottom:1px solid #dce0e5}.purchase-document td:not(:first-child),.purchase-document th:not(:first-child){text-align:right;white-space:nowrap}.purchase-document .document-totals{max-width:330px;margin-left:auto}.document-totals p{display:flex;justify-content:space-between;gap:20px;padding:4px 0}.document-total{border-top:2px solid #17202a;margin-top:10px;font-size:16px}.purchase-document footer{border-top:1px solid #dce0e5;padding-top:20px;text-align:center;font-size:11px}.purchase-document td small{display:block;margin-top:4px;color:#56616c}.purchase-document p{overflow-wrap:anywhere}.purchase-document{box-sizing:border-box;width:718px;max-width:100%;print-color-adjust:exact;-webkit-print-color-adjust:exact}.purchase-export{width:718px;max-width:none;border-radius:12px}.purchase-document th:first-child{width:52%}@media print{.purchase-export{width:100%;max-width:none}.purchase-document{font:13px/1.5 Arial,sans-serif}}`}</style>
 </article>;
}
