import { useEffect, useState } from 'react';
import { Link, useSearchParams } from '@/lib/router';
import { useDatabase } from '@/lib/backend';
import { supabase } from '@/lib/backend/client';
import { useAuthStore } from '@/store/authStore';
import { toast } from 'sonner';

export default function PagoPage() {
 const database=useDatabase(); const [params]=useSearchParams();const {user,fetchProfile}=useAuthStore();
 const [methods,setMethods]=useState<any[]>([]);const [selected,setSelected]=useState(params.get('method')||'');
 const [session,setSession]=useState<any>(null);const [plan,setPlan]=useState<any>(null);
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [reference,setReference]=useState('');const [file,setFile]=useState<File|null>(null);
 const cancelled=params.get('cancel')==='1';const sessionId=params.get('session');const planSlug=params.get('plan');const orderId=params.get('order');
 const invoke=async(body:any)=>{const {data,error}=await database.invoke<any>('process-payment',{body});if(error||!data?.success)throw new Error(data?.error||'No se pudo conectar con el servicio de pagos.');return data;};
 const refresh=async(id:string)=>{const {data,error}=await database.select<any>('payment_sessions',{filter:{id},single:true});if(error)throw new Error('No se pudo cargar el pago.');setSession(data);return data;};
 useEffect(()=>{if(!user)return;let live=true;invoke({action:'methods'}).then(d=>{if(live)setMethods(d.methods)}).catch(e=>setError(e.message));if(orderId)database.select('orders',{filter:{id:orderId},single:true}).then(({data})=>setPlan(data));if(planSlug)database.select('plans',{filter:{slug:planSlug,is_active:true},single:true}).then(({data})=>setPlan(data));return()=>{live=false}},[user?.id,planSlug,orderId]);
 useEffect(()=>{if(!user||!sessionId)return;setBusy(true);setError('');(cancelled?Promise.resolve({status:'pending'}):invoke({action:'verify',session_id:sessionId})).then(async d=>{await refresh(sessionId);if(d.status==='paid')await fetchProfile(user.id)}).catch(e=>setError(e.message)).finally(()=>setBusy(false));},[sessionId,user?.id,cancelled]);
 const method=methods.find(m=>m.slug===(session?.gateway||selected));
 const start=async()=>{setBusy(true);setError('');try{const d=await invoke({gateway:selected,plan_slug:planSlug,order_id:orderId});if(d.redirect_url){window.location.assign(d.redirect_url);return}await refresh(d.session_id);window.history.replaceState({},'',`/pago?session=${d.session_id}`)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const verify=async()=>{if(!session)return;setBusy(true);try{const d=await invoke({action:'verify',session_id:session.id});await refresh(session.id);if(d.status==='paid'&&user)await fetchProfile(user.id);else toast.info('El pago aún está pendiente de confirmación.')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const upload=async()=>{if(!file||!user||!reference.trim())return;setBusy(true);setError('');try{if(file.size>5*1024*1024)throw new Error('El archivo debe pesar menos de 5 MB.');if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type))throw new Error('Adjunta una imagen o PDF.');const path=`${user.id}/${crypto.randomUUID()}.${file.type==='application/pdf'?'pdf':file.type.split('/')[1]}`;const {error}=await supabase.storage.from('payment-receipts').upload(path,file);if(error)throw new Error('No se pudo subir el comprobante.');await invoke({action:'receipt',session_id:session.id,path,reference});await refresh(session.id);toast.success('Comprobante enviado para revisión.')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 let accounts:any[]=[];try{accounts=JSON.parse(method?.credentials?.accounts||'[]')}catch{}
 const button='px-5 py-3 rounded-xl bg-primary text-white font-medium disabled:opacity-50';
 return <main className="max-w-2xl mx-auto w-full px-5 pt-28 pb-16 space-y-6"><Link to={session?.order_id?'/dashboard/pedidos':'/dashboard/mi-plan'} className="text-sm text-muted-foreground">← Volver a {session?.order_id?'mis pedidos':'mi plan'}</Link><h1 className="text-2xl font-bold">{session?'Tu pago':orderId?'Completa el pago de tu pedido':'Completa tu membresía'}</h1>
 {!user?<p><Link to="/login" className="text-primary">Inicia sesión</Link> para continuar.</p>:<>
 {error&&<p role="alert" className="text-red-500">{error}</p>}
 {!session&&<><p className="text-muted-foreground">{plan?.name||plan?.order_number} · Elige cómo pagar. El importe final se mostrará en la moneda del método seleccionado.</p><div className="space-y-2">{methods.filter(m=>m.ready).map(m=><button key={m.slug} onClick={()=>setSelected(m.slug)} aria-pressed={selected===m.slug} className={`w-full text-left p-4 rounded-xl border ${selected===m.slug?'border-primary bg-primary/5':'border-border'}`}><span className="font-medium">{m.logo} {m.name}</span><span className="block text-sm text-muted-foreground mt-1">{['paypal','mercadopago'].includes(m.slug)?'Paga en el checkout seguro de '+m.name:'Pago manual con comprobante'} · {m.currency}</span></button>)}</div><button className={button} disabled={busy||!selected||!plan} onClick={start}>{busy?'Conectando…':'Continuar'}</button></>}
 {session&&<><p className="text-lg font-semibold">{session.currency} {Number(session.amount).toFixed(2)} · {method?.name||session.gateway}</p><p className="text-xs text-muted-foreground break-all">Referencia: {session.id}</p>
 {session.status==='paid'?<p role="status" className="text-emerald-500">Pago confirmado. {session.order_id?'Tu pedido está pagado.':'Tu membresía está activa.'}</p>:session.status==='review'?<p role="status">Recibimos tu comprobante. El pago está pendiente de revisión administrativa.</p>:session.status==='rejected'?<p role="alert">El comprobante fue rechazado. Contacta con soporte para revisar el pago.</p>:['yape','plin','transfer'].includes(session.gateway)?<div className="space-y-5"><p>Realiza el pago y adjunta el comprobante. La confirmación es manual.</p>{session.gateway==='transfer'?accounts.map((a:any,i:number)=><div key={i} className="space-y-1"><p className="font-semibold">{a.bank} · {a.currency||'PEN'}</p><p>{a.holder}</p><p className="font-mono text-sm">Cuenta: {a.number}</p>{a.cci&&<p className="font-mono text-sm">CCI: {a.cci}</p>}</div>):<div><p className="font-semibold">{method?.credentials?.merchant_name}</p><p className="text-xl font-mono">{method?.credentials?.phone_number}</p></div>}<label className="block text-sm">Número de operación<input value={reference} onChange={e=>setReference(e.target.value)} maxLength={100} className="block w-full mt-2 rounded-lg border border-border bg-background p-3"/></label><label className="block text-sm">Comprobante (imagen o PDF, máximo 5 MB)<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)} className="block mt-2 w-full"/></label><button onClick={upload} disabled={busy||!file||!reference.trim()} className={button}>{busy?'Enviando…':'Enviar comprobante'}</button></div>:<div className="space-y-4"><p>Verificamos el estado directamente con {method?.name||session.gateway}. Si cancelaste el checkout, puedes retomarlo.</p><div className="flex flex-wrap gap-3">{session.checkout_url&&<a href={session.checkout_url} className={button}>Continuar al checkout</a>}<button onClick={verify} disabled={busy} className="px-5 py-3 border border-border rounded-xl">{busy?'Verificando…':'Verificar pago'}</button></div></div>}</>}
 </>}
 </main>;
}
