import {useEffect,useState} from 'react';
import {Link} from '@/lib/router';
import {useBackend} from '@/lib/backend';
import {AuthLayout,authInput,authButton} from '@/components/auth/AuthLayout';
import {Eye,EyeOff,CheckCircle} from 'lucide-react';
export default function ResetPasswordPage(){
 const backend=useBackend();const [checking,setChecking]=useState(true),[valid,setValid]=useState(false),[done,setDone]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[show,setShow]=useState(false);
 useEffect(()=>{let active=true;const recovery=window.location.hash.includes('type=recovery')||new URLSearchParams(window.location.search).get('type')==='recovery';backend.auth.getSession().then(session=>{if(active){setValid(!!session&&recovery);setChecking(false);}}).catch(()=>{if(active)setChecking(false);});return()=>{active=false;};},[backend.auth]);
 return <AuthLayout title="Nueva contraseña">{checking?<div className="min-h-36" aria-busy="true"/>:done?<div className="space-y-4"><CheckCircle className="text-primary"/><p role="status">Tu contraseña se actualizó correctamente.</p><Link to="/dashboard" className={authButton+' flex items-center justify-center'}>Continuar</Link></div>:!valid?<div className="space-y-5"><p className="text-sm text-muted-foreground">Este enlace venció o no es válido. Solicita uno nuevo para cambiar tu contraseña.</p><Link to="/login" className={authButton+' flex items-center justify-center'}>Volver a ingresar</Link></div>:<form className="space-y-4" onSubmit={async e=>{e.preventDefault();setError('');if(password.length<8){setError('Usa al menos 8 caracteres.');return;}if(password!==confirm){setError('Las contraseñas no coinciden.');return;}setBusy(true);const result=await backend.auth.updatePassword(password);setBusy(false);if(result.error)setError('No pudimos cambiar la contraseña. Intenta nuevamente.');else setDone(true);}}>
 <p className="text-sm text-muted-foreground">Elige una contraseña de al menos 8 caracteres.</p>
 <label className="block text-sm font-medium">Nueva contraseña<div className="relative"><input required minLength={8} autoComplete="new-password" type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} className={authInput+' pr-12'}/><button type="button" aria-label={show?'Ocultar contraseña':'Mostrar contraseña'} onClick={()=>setShow(!show)} className="absolute right-2 top-1.5 p-2 text-muted-foreground">{show?<EyeOff size={20}/>:<Eye size={20}/>}</button></div></label>
 <label className="block text-sm font-medium">Repite la contraseña<input required autoComplete="new-password" type={show?'text':'password'} value={confirm} onChange={e=>setConfirm(e.target.value)} className={authInput}/></label>
 {error&&<p role="alert" className="text-sm text-red-500">{error}</p>}<div className="form-actions"><button disabled={busy} className={authButton}>{busy?'Guardando…':'Guardar contraseña'}</button></div></form>}</AuthLayout>;
}
