import {useEffect,useState} from 'react';
import {useDatabase} from '@/lib/backend';
import {useAuthStore} from '@/store/authStore';
import {useConfig,formatPrice} from '@/store/configStore';
import {useNavigate,useSearchParams} from '@/lib/router';
import {planTerms} from '@/lib/planTerms';
import {PaymentCurrency} from '@/components/payments/PaymentMethods';
import {LoadingRegion} from '@/components/ui/loading-region';
import {CalendarDays,Check,ArrowRight,CreditCard,Clock,ShieldCheck} from 'lucide-react';
import {toast} from 'sonner';
const panel='rounded-xl border border-border bg-card p-5 sm:p-6';
const secondary='inline-flex items-center justify-center gap-2 rounded-lg border border-border px-4 py-2.5 text-sm font-medium hover:bg-muted disabled:opacity-50';
const primary='inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground disabled:opacity-50';
const displayDate=(v:number)=>Number.isFinite(v)?new Date(v).toLocaleDateString('es-PE',{day:'numeric',month:'long',year:'numeric'}):'No registrada';
export default function MyPlanPage(){
 const database=useDatabase();const {user,fetchProfile}=useAuthStore();const {company,plans,loading:configLoading,showUsd,setShowUsd,currencySymbol,exchangeRate}=useConfig();const navigate=useNavigate();const [params]=useSearchParams();
 const [tab,setTab]=useState(params.get('tab')==='change'?'plans':'current');const [sub,setSub]=useState<any>(null);const [contracts,setContracts]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [reload,setReload]=useState(0);const [busy,setBusy]=useState(false);const [cancel,setCancel]=useState(false);
 useEffect(()=>{if(!user?.id)return;let alive=true;setLoading(true);setError(false);Promise.all([database.select<any>('subscriptions',{filter:{user_id:user.id},limit:1,maybeSingle:true}),database.select<any>('billing_contracts',{filter:{user_id:user.id,status:['pending','active','suspended']},order:{column:'created_at',ascending:false}})]).then(([s,c])=>{if(!alive)return;if(s.error||c.error)setError(true);else{setSub(s.data);setContracts(Array.isArray(c.data)?c.data:[]);}setLoading(false);}).catch(()=>{if(alive){setError(true);setLoading(false);}});return()=>{alive=false;};},[user?.id,reload]);
 const offered=company.system_plans_enabled!=='false';const plan=plans.find(p=>p.slug===(sub?.plan_slug||user?.plan));const terms=planTerms(sub,plan);const currency=showUsd?'USD':'PEN';const pending=contracts.find(c=>c.status==='pending');const recurring=contracts.find(c=>c.id===sub?.contract_id)||contracts.find(c=>c.status==='active'||c.status==='suspended');const choices=plans.filter(p=>p.is_active).sort((a,b)=>a.sort_order-b.sort_order);
 const mutate=async(action:()=>Promise<any>,message:string)=>{if(busy)return;setBusy(true);try{const {data,error}=await action();if(error||!data?.success)throw new Error(data?.error||error?.message||'No se pudo completar la acción.');toast.success(message);if(user)await fetchProfile(user.id);setCancel(false);setReload(n=>n+1);}catch(e:any){toast.error(e.message);}finally{setBusy(false);}};
 const discard=()=>pending&&mutate(()=>database.invoke('subscription-billing',{body:{action:'cancel',contract_id:pending.id}}),'Autorización descartada.');
 const choose=(p:any)=>{if(!offered||busy)return;if(pending){navigate(`/pago?subscription=${pending.id}`);return;}if(p.is_free||Number(p.price)===0)mutate(()=>database.invoke('process-payment',{body:{action:'free_plan',plan_slug:p.slug}}),'Plan activado.');else navigate(`/pago?plan=${encodeURIComponent(p.slug)}&currency=${currency}`);};
 if(loading||configLoading)return <LoadingRegion className="min-h-[60vh]"/>;
 if(error)return <div className={panel} role="alert"><p>No pudimos consultar tu membresía.</p><button className={`${secondary} mt-4`} onClick={()=>setReload(n=>n+1)}>Reintentar</button></div>;
 const progress=Number.isFinite(terms.end)&&Number.isFinite(terms.start)?Math.max(0,Math.min(100,(Date.now()-terms.start)/(terms.end-terms.start)*100)):0;
 return <div className="max-w-6xl space-y-6"><header className="flex flex-wrap justify-between items-start gap-4"><div><h1 className="text-2xl font-bold">Mi plan</h1><p className="mt-2 text-sm text-muted-foreground">Tu membresía, vigencia y próximos pagos.</p></div>{tab==='current'&&offered&&<button className={secondary} onClick={()=>setTab('plans')}>Ver planes<ArrowRight size={16}/></button>}</header>
 {offered&&<nav className="flex gap-6 border-b border-border" aria-label="Membresía">{[['current','Mi membresía'],['plans','Planes disponibles']].map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)} className={`pb-3 text-sm font-medium border-b-2 ${tab===id?'text-primary border-primary':'text-muted-foreground border-transparent'}`}>{label}</button>)}</nav>}
 {!offered&&<div className={panel}><p className="font-medium">No se ofrecen nuevas membresías</p><p className="mt-2 text-sm text-muted-foreground">Tu cuenta y la tienda siguen disponibles. Puedes consultar tu membresía y gestionar una renovación existente.</p></div>}
 {pending&&<section className={panel}><div className="flex flex-col sm:flex-row justify-between gap-5"><div><h2 className="font-semibold flex items-center gap-2"><Clock size={18} className="text-primary"/>Autorización por completar</h2><p className="mt-2 text-sm text-muted-foreground">{plans.find(p=>p.slug===pending.plan_slug)?.name||pending.plan_slug} · {pending.currency} {Number(pending.amount).toFixed(2)} / mes · {pending.gateway}</p><p className="mt-2 text-sm text-muted-foreground">La autorización pendiente no activa ni modifica tu membresía.</p></div><div className="flex flex-wrap items-center gap-3 shrink-0">{offered&&<button className={primary} onClick={()=>navigate(`/pago?subscription=${pending.id}`)}>Continuar</button>}<button disabled={busy} className={secondary} onClick={discard}>Descartar</button></div></div></section>}
 {(tab==='current'||!offered)?<>
 <div className="grid lg:grid-cols-3 gap-5"><section className={`${panel} lg:col-span-2 space-y-6`}><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">Membresía contratada</p><h2 className="mt-2 text-2xl font-semibold">{sub?(plan?.name||sub.plan_slug):'Sin membresía activa'}</h2>{plan?.description&&<p className="mt-2 text-sm text-muted-foreground">{plan.description}</p>}</div><span className={`shrink-0 rounded-full px-3 py-1 text-sm ${terms.active?'bg-primary/10 text-primary':'bg-muted text-foreground'}`}>{terms.status}</span></div>
 {sub?<><div className="grid sm:grid-cols-2 gap-5 border-y border-border py-5"><div><p className="text-sm text-muted-foreground flex items-center gap-2"><CalendarDays size={16}/>Inicio del período</p><p className="mt-2 font-medium">{displayDate(terms.start)}</p></div><div><p className="text-sm text-muted-foreground">{terms.expired?'Finalizó el':'Vence el'}</p><p className="mt-2 font-medium">{Number.isFinite(terms.end)?displayDate(terms.end):terms.free&&terms.days===0?'Sin fecha de vencimiento configurada':'Fecha no registrada'}</p></div></div>
 {Number.isFinite(terms.end)&&<div><div className="flex justify-between gap-3 text-sm mb-3"><span>{terms.free&&terms.days>0?`Prueba de ${terms.days} días`:'Vigencia del período'}</span><span className="font-medium">{terms.expired?'Período finalizado':`${terms.remaining} días restantes`}</span></div><div className="h-2 rounded-full bg-muted overflow-hidden"><div className="h-full bg-primary" style={{width:`${progress}%`}}/></div></div>}
 {terms.expired&&<p className="text-sm text-muted-foreground">Los beneficios de esta membresía ya vencieron.{offered?' Elige un plan disponible para volver a activarlos.':''}</p>}
 </>:<p className="text-sm text-muted-foreground">Puedes usar tu cuenta y comprar en la tienda.{offered?' Explora los planes si deseas activar sus beneficios.':''}</p>}
 </section><section className={`${panel} flex flex-col gap-5`}><h2 className="font-semibold flex items-center gap-2"><CreditCard size={18} className="text-primary"/>Pagos y renovación</h2><div><p className="text-sm text-muted-foreground">Importe del período</p><p className="mt-2 text-2xl font-semibold">{sub?terms.free?'Gratis':`${sub.currency||'PEN'} ${Number(sub.amount||0).toFixed(2)}`:'—'}</p></div><dl className="space-y-4 text-sm"><div><dt className="text-muted-foreground">Renovación</dt><dd className="mt-1 font-medium">{!sub?'No aplica':terms.free?'No automática':sub.cancel_at_period_end?'Cancelada':sub.auto_renew?'Automática mensual':'Pago único'}</dd></div><div><dt className="text-muted-foreground">Método</dt><dd className="mt-1 font-medium">{terms.free?'Sin cobro':sub?.gateway||'No registrado'}</dd></div></dl>
 {recurring&&!sub?.cancel_at_period_end&&<button className={`${secondary} mt-auto`} onClick={()=>setCancel(true)}>Cancelar renovación</button>}{offered&&terms.expired&&<button className={`${primary} mt-auto`} onClick={()=>setTab('plans')}>Elegir plan<ArrowRight size={16}/></button>}</section></div>
 {cancel&&<section className={panel} role="alert"><h2 className="font-semibold">¿Cancelar las próximas renovaciones?</h2><p className="mt-2 text-sm text-muted-foreground">No se cobrarán nuevos períodos. {terms.active&&Number.isFinite(terms.end)?`Conservas los beneficios hasta el ${displayDate(terms.end)}.`:''} Esta acción no genera un reembolso.</p><div className="flex flex-wrap justify-end gap-3 border-t border-border pt-4 mt-5"><button className={secondary} onClick={()=>setCancel(false)}>Mantener renovación</button><button disabled={busy} className={primary} onClick={()=>mutate(()=>database.invoke('subscription-billing',{body:{action:'cancel',contract_id:recurring?.id}}),'Renovación cancelada.')}>Confirmar cancelación</button></div></section>}
 {plan&&<section className={panel}><h2 className="font-semibold flex items-center gap-2"><ShieldCheck size={18} className="text-primary"/>Beneficios de {plan.name}</h2><p className="mt-2 text-sm text-muted-foreground">{terms.active?'Disponibles durante la vigencia de tu membresía.':'Se habilitan con una membresía vigente.'}</p><ul className="grid sm:grid-cols-2 gap-x-8 gap-y-4 mt-5">{plan.features.map((feature,i)=><li key={i} className="flex gap-3 text-sm"><Check size={17} className="shrink-0 text-primary"/>{feature}</li>)}</ul></section>}
 </>:<><div className="flex flex-wrap justify-between items-center gap-4"><p className="text-sm text-muted-foreground">Compara las condiciones antes de elegir.</p><PaymentCurrency value={currency} onChange={v=>setShowUsd(v==='USD')}/></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{choices.map(p=>{const current=p.slug===sub?.plan_slug&&terms.active;const free=p.is_free||Number(p.price)===0;return <section key={p.id} className={`${panel} flex flex-col gap-5`} style={p.color?.startsWith('#')?{borderTopColor:p.color,borderTopWidth:3}:undefined}><div className="flex justify-between gap-3"><h2 className="text-xl font-semibold">{p.name}</h2>{(current||p.badge)&&<span className="text-sm text-primary">{current?'Tu plan':p.badge}</span>}</div><p className="text-sm text-muted-foreground">{p.description}</p><div><p className="text-3xl font-semibold">{free?'Gratis':formatPrice(p.price,currency,currencySymbol,exchangeRate)}</p><p className="mt-2 text-sm text-muted-foreground">{free?(p.trial_days>0?`${p.trial_days} días de acceso`:'Sin duración limitada'):'Un mes de acceso'}{!free&&p.trial_days>0?` · ${p.trial_days} días de prueba según las condiciones del plan`:''}</p></div><ul className="space-y-3 border-t border-border pt-5">{p.features.map((f,i)=><li key={i} className="flex gap-2 text-sm"><Check size={16} className="shrink-0 text-primary"/>{f}</li>)}</ul><button disabled={busy||current} className={`${current?secondary:primary} mt-auto`} onClick={()=>choose(p)}>{current?'Plan actual':pending?'Revisar autorización':free?'Activar plan':'Elegir plan'}{!current&&<ArrowRight size={16}/>}</button></section>;})}</div>{!choices.length&&<p className={panel}>No hay planes disponibles en este momento.</p>}</>}
 </div>;
}
