import NotificationInbox from '@/components/settings/NotificationInbox';
import {useConfig} from '@/store/configStore';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/backend/client';
import {useThemeStore} from '@/store/themeStore';
import {useAuthStore} from '@/store/authStore';
import {Link} from '@/lib/router';
import {LoadingRegion} from '@/components/ui/loading-region';
import {Switch} from '@/components/ui/switch';
import {Sun,Moon,Monitor,Save,ArrowRight} from 'lucide-react';
import {toast} from 'sonner';
const defaults={new_affiliates:true,commissions:true,rank_changes:true,promotions:false};
type Preferences=typeof defaults;
export default function SettingsPage(){
 const {user,getInviteLink}=useAuthStore();const {ranks,company}=useConfig();const {theme,setTheme}=useThemeStore();const [tab,setTab]=useState('account');const [permissions,setPermissions]=useState<Record<string,boolean>>({});const [prefs,setPrefs]=useState<Preferences>(defaults);const [saved,setSaved]=useState<Preferences>(defaults);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [saving,setSaving]=useState(false);const [attempt,setAttempt]=useState(0);
 useEffect(()=>{if(!user)return;let alive=true;setLoading(true);setError(false);Promise.all([supabase.rpc('account_capabilities'),supabase.from('notification_preferences').select('new_affiliates,commissions,rank_changes,promotions').eq('user_id',user.id).maybeSingle()]).then(([p,n])=>{if(!alive)return;if(p.error||n.error)setError(true);else{setPermissions(p.data||{});setPrefs(n.data||defaults);setSaved(n.data||defaults);}setLoading(false);}).catch(()=>{if(alive){setError(true);setLoading(false);}});return()=>{alive=false;};},[user?.id,attempt]);
 const save=async()=>{if(!user||saving)return;setSaving(true);try{const r=await supabase.from('notification_preferences').upsert({...prefs,user_id:user.id,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(r.error)throw r.error;setSaved({...prefs});toast.success('Preferencias guardadas');}catch{toast.error('No se pudieron guardar. Tus cambios siguen aquí para reintentar.');}finally{setSaving(false);}};
 const items:{key:keyof Preferences;label:string;desc:string;show:boolean}[]=[{key:'new_affiliates',label:'Nuevos referidos',desc:'Avisarme cuando una persona se una a mi red directa.',show:!!permissions.view_network},{key:'commissions',label:'Comisiones aprobadas',desc:'Avisarme cuando una comisión esté aprobada o pagada.',show:!!permissions.view_commissions},{key:'rank_changes',label:'Cambios de rango',desc:'Avisarme cuando cambie mi rango en la red.',show:!!permissions.view_network},{key:'promotions',label:'Promociones',desc:'Recibir novedades comerciales dentro del sistema.',show:true}];
 const actions=[{show:permissions.view_network,title:'Mi red',text:'Consulta tus referidos y la estructura de tu red.',to:'/dashboard/red'},{show:permissions.view_commissions,title:'Mis comisiones',text:'Consulta los movimientos, importes y estados de tus comisiones.',to:'/dashboard/comisiones'},{show:permissions.manage_mlm_commissions,title:'Reglas de comisión de productos',text:'Gestiona la matriz de comisiones por rango y nivel.',to:'/dashboard/admin/comisiones-mlm'},{show:permissions.configure_system,title:'Planes y packs',text:'Configura los beneficios de membresía y las comisiones de cada pack.',to:'/dashboard/admin?module=planes'},{show:permissions.configure_system,title:'Registro y referidos',text:'Administra los requisitos de registro y el referido predeterminado.',to:'/dashboard/admin?module=registro'}].filter(x=>x.show);
 return <div className="max-w-5xl space-y-7"><header><h1 className="text-2xl font-bold">Configuración</h1><p className="mt-2 text-sm text-muted-foreground">Administra tu cuenta, tu red y cómo recibes tus avisos.</p></header><nav className="flex gap-6 overflow-x-auto border-b border-border" aria-label="Secciones de configuración">{[['account','Cuenta y seguridad'],['mlm','Red MLM'],['notifications','Notificaciones'],['appearance','Apariencia'],...(permissions.configure_system?[['system','Administración']]:[])].map(([id,label])=><button key={id} onClick={()=>setTab(id)} aria-current={tab===id?'page':undefined} className={`shrink-0 border-b-2 pb-3 text-sm ${tab===id?'border-primary text-primary':'border-transparent text-muted-foreground'}`}>{label}</button>)}</nav>
 {loading?<LoadingRegion className="min-h-80"/>:error?<div role="alert" className="space-y-4"><p>No se pudo cargar tu configuración.</p><button onClick={()=>setAttempt(a=>a+1)} className="text-primary underline">Reintentar</button></div>:<>
 {tab==='account'&&<div className="grid lg:grid-cols-2 gap-5"><section className="rounded-xl border border-border bg-card p-6"><h2 className="text-lg font-semibold">Tu cuenta</h2><dl className="mt-5 divide-y divide-border text-sm">{[['Nombre',user?.full_name],['Correo',user?.email],['Teléfono',user?.phone||'No registrado'],['Miembro desde',user?.created_at?new Date(user.created_at).toLocaleDateString('es-PE'):'—']].map(([label,value])=><div key={label} className="py-4"><dt className="text-muted-foreground">{label}</dt><dd className="mt-1 font-medium break-words">{value}</dd></div>)}</dl><div className="flex justify-end border-t border-border pt-5"><Link className="text-sm text-primary" to="/dashboard/perfil">Editar datos y foto <ArrowRight className="inline ml-1" size={15}/></Link></div></section><section className="rounded-xl border border-border bg-card p-6"><h2 className="text-lg font-semibold">Seguridad y acceso</h2><div className="divide-y divide-border mt-5"><div className="py-4"><h3 className="font-medium text-sm">Correo de la cuenta</h3><p className="mt-2 text-sm text-muted-foreground">{user?.email_confirmed?'Correo confirmado.':'Tu correo todavía no está confirmado. La verificación está disponible desde el aviso de tu cuenta.'}</p></div><div className="py-4"><h3 className="font-medium text-sm">Contraseña</h3><p className="mt-2 text-sm text-muted-foreground">Actualiza tu contraseña desde tu perfil.</p><Link className="mt-3 inline-block text-sm text-primary" to="/dashboard/perfil">Gestionar contraseña</Link></div><div className="py-4"><h3 className="font-medium text-sm">Tus pedidos y comprobantes</h3><p className="mt-2 text-sm text-muted-foreground">Consulta compras, entregas y documentos de pago.</p><Link className="mt-3 inline-block text-sm text-primary" to="/dashboard/pedidos">Ver mis pedidos</Link></div>{company.system_plans_enabled!=='false'&&<div className="py-4"><Link className="text-sm text-primary" to="/dashboard/mi-plan">Gestionar mi membresía</Link></div>}</div></section></div>}
 {tab==='system'&&permissions.configure_system&&<section className="rounded-xl border border-border bg-card p-6"><h2 className="text-lg font-semibold">Administración del sistema</h2><p className="text-sm text-muted-foreground mt-2">Configuraciones compartidas por toda la organización.</p><div className="grid sm:grid-cols-2 gap-x-8 mt-5">{[['Empresa','Identidad, datos de contacto y logotipo.','empresa'],['Mantenimiento','Aviso público y fecha de reapertura.','mantenimiento'],['Planes y packs','Disponibilidad, precios y beneficios.','planes'],['Registro','Requisitos y código de referido.','registro'],['Permisos','Accesos y funciones por cargo.','permisos'],['Correos','Configuración de los correos del sistema.','correos']].map(([title,desc,module])=><Link key={module} to={'/dashboard/admin?module='+module} className="flex items-center justify-between gap-4 py-5 border-b border-border"><span><span className="block font-medium">{title}</span><span className="mt-2 block text-sm text-muted-foreground">{desc}</span></span><ArrowRight size={18}/></Link>)}</div></section>}
 {tab==='mlm'&&<section className="space-y-5 rounded-xl border border-border bg-card p-5 sm:p-6"><div><h2 className="text-lg font-semibold">Red MLM</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{permissions.configure_system?'Gestiona cada regla desde su apartado. Los productos, packs y planes conservan sus propias condiciones.':'Consulta la información y las opciones disponibles para tu cargo.'}</p></div>{permissions.view_network&&<div className="grid sm:grid-cols-2 gap-5 border-y border-border py-5"><div><p className="text-sm text-muted-foreground">Tu rango actual</p><p className="mt-2 font-semibold">{ranks.find(r=>r.slug===user?.rank)?.name||user?.rank||'Sin rango'}</p><Link to="/dashboard/rangos" className="mt-3 inline-block text-sm text-primary">Ver requisitos y beneficios</Link></div><div><p className="text-sm text-muted-foreground">Tu código de referido</p><p className="mt-2 font-semibold break-all">{user?.referral_code||'No asignado'}</p>{getInviteLink()&&<button className="mt-3 text-sm text-primary" onClick={async()=>{try{await navigator.clipboard.writeText(getInviteLink());toast.success('Enlace de invitación copiado');}catch{toast.error('No se pudo copiar el enlace.');}}}>Copiar enlace de invitación</button>}</div></div>}<div className="divide-y divide-border">{actions.map(a=><Link key={a.to} to={a.to} className="flex items-center justify-between gap-6 py-5"><span><span className="block font-medium">{a.title}</span><span className="block mt-2 text-sm text-muted-foreground">{a.text}</span></span><ArrowRight size={18} className="shrink-0 text-muted-foreground"/></Link>)}</div>{!actions.length&&<p className="text-sm text-muted-foreground">Tu cargo no tiene funciones de gestión de red asignadas.</p>}</section>}
 {tab==='appearance'&&<section className="space-y-5 rounded-xl border border-border bg-card p-5 sm:p-6"><div><h2 className="text-lg font-semibold">Apariencia en este dispositivo</h2><p className="mt-2 text-sm text-muted-foreground">Elige cómo prefieres ver el sistema. Se aplica al instante.</p></div><div className="flex flex-wrap gap-3">{([{id:'light',label:'Claro',Icon:Sun},{id:'dark',label:'Oscuro',Icon:Moon},{id:'system',label:'Automático',Icon:Monitor}] as const).map(({id,label,Icon})=><button key={id} aria-pressed={theme===id} onClick={()=>setTheme(id)} className={`flex items-center gap-3 rounded-lg border px-5 py-3 ${theme===id?'border-primary text-primary':'border-border'}`}><Icon size={18}/>{label}</button>)}</div></section>}
 {tab==='notifications'&&<><NotificationInbox/><section className="rounded-xl border border-border bg-card p-5 sm:p-6"><h2 className="text-lg font-semibold">Preferencias de avisos</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Elige qué novedades recibir en el centro de notificaciones. Los cambios se aplican a los avisos nuevos.</p><div className="mt-5 divide-y divide-border">{items.filter(i=>i.show).map(i=><div key={i.key} className="flex items-center justify-between gap-6 py-5"><label htmlFor={i.key} className="cursor-pointer"><span className="block font-medium text-sm">{i.label}</span><span className="mt-2 block text-sm text-muted-foreground">{i.desc}</span></label><Switch id={i.key} checked={prefs[i.key]} disabled={saving} onCheckedChange={v=>setPrefs(p=>({...p,[i.key]:v}))}/></div>)}</div><div className="mt-5 rounded-lg border border-border p-4"><h3 className="text-sm font-semibold">Avisos necesarios · Siempre activos</h3><p className="mt-2 text-sm text-muted-foreground">Confirmaciones de pago, revisión de comprobantes, seguridad y cambios de suscripción. No se desactivan con estas preferencias.</p><p className="mt-2 text-sm text-muted-foreground">Los comprobantes enviados por correo se gestionan por separado; estas opciones controlan los avisos del panel.</p></div><footer className="mt-4 flex justify-end border-t border-border pt-5"><button disabled={saving||JSON.stringify(prefs)===JSON.stringify(saved)} onClick={save} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-primary px-5 py-2 text-primary-foreground disabled:opacity-50"><Save size={17}/>{saving?'Guardando…':'Guardar preferencias'}</button></footer></section></>}
 </>}
 </div>;
}
