import {useMemo,useState} from 'react';
import MlmPointsSummary from '@/components/MlmPointsSummary';
import {LoadingRegion} from '@/components/ui/loading-region';
import {useAuthStore} from '@/store/authStore';
import {useCommissions,TYPE_LABELS} from '@/modules/mlm';
import {mlmService,STATUS_CONFIG} from '@/modules/mlm/services/mlmService';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {BarChart,Bar,ResponsiveContainer,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import {Download,RefreshCw} from 'lucide-react';
export default function CommissionsPage(){
 const {user}=useAuthStore();const {commissions,loading,error,refresh}=useCommissions({userId:user?.id});
 const [currency,setCurrency]=useState('PEN');const [status,setStatus]=useState('all');const [search,setSearch]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [page,setPage]=useState(0);
 const rows=useMemo(()=>commissions.filter(c=>c.currency===currency&&(status==='all'||c.status===status)&&(!from||c.created_at.slice(0,10)>=from)&&(!to||c.created_at.slice(0,10)<=to)&&(!search||`${c.description||''} ${TYPE_LABELS[c.type]||c.type}`.toLowerCase().includes(search.toLowerCase()))),[commissions,currency,status,from,to,search]);
 const money=(n:number)=>new Intl.NumberFormat('es-PE',{style:'currency',currency}).format(n);const sum=(s:string)=>rows.filter(r=>r.status===s).reduce((n,r)=>n+Number(r.amount),0);const chart=mlmService.buildCommissionChartData(rows);const pages=Math.max(1,Math.ceil(rows.length/10));const current=Math.min(page,pages-1);
 if(loading)return <LoadingRegion className="min-h-[60vh]"/>;
 return <div className="space-y-6 pb-8"><header className="flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-bold">Mis comisiones</h1><p className="text-sm text-muted-foreground mt-2">Tus movimientos en dinero, separados por moneda y estado.</p></div><div className="flex gap-2"><button aria-label="Actualizar comisiones" onClick={refresh} className="p-3 border border-border rounded-xl"><RefreshCw className="w-4 h-4"/></button><button disabled={!rows.length} onClick={()=>mlmService.exportCommissionsToCSV(rows)} className="flex items-center gap-2 border border-border px-4 py-2 rounded-xl text-sm disabled:opacity-50"><Download className="w-4 h-4"/>Exportar resultados</button></div></header>
 {error&&<p role="alert" className="text-destructive">{error}</p>}
 <section className="bg-card border border-border rounded-xl p-5 grid sm:grid-cols-2 xl:grid-cols-5 gap-4 items-end"><label className="text-sm space-y-2"><span className="block">Moneda</span><Select value={currency} onValueChange={v=>{setCurrency(v);setPage(0);}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Array.from(new Set(['PEN','USD',...commissions.map(c=>c.currency)])).map(c=><SelectItem key={c} value={c}>{c==='PEN'?'Soles (PEN)':c==='USD'?'Dólares (USD)':c}</SelectItem>)}</SelectContent></Select></label><label className="text-sm space-y-2"><span className="block">Estado</span><Select value={status} onValueChange={v=>{setStatus(v);setPage(0);}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos</SelectItem>{Object.entries(STATUS_CONFIG).map(([k,v])=><SelectItem key={k} value={k}>{v.label}</SelectItem>)}</SelectContent></Select></label>{[{name:'Desde',value:from,set:setFrom},{name:'Hasta',value:to,set:setTo}].map(d=><label key={d.name} className="text-sm space-y-2"><span className="block">{d.name}</span><input type="date" value={d.value} onChange={e=>{d.set(e.target.value);setPage(0);}} className="h-10 px-3 border border-border bg-background rounded-lg w-full"/></label>)}<label className="text-sm space-y-2"><span className="block">Buscar movimiento</span><input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="Tipo o descripción" className="h-10 px-3 border border-border bg-background rounded-lg w-full"/></label></section>
 <div className="grid sm:grid-cols-3 gap-4">{[{label:'Pendiente de aprobación',value:sum('pending')},{label:'Aprobado, pendiente de pago',value:sum('approved')},{label:'Pagado',value:sum('paid')}].map(x=><section key={x.label} className="p-5 rounded-xl bg-card border border-border"><p className="text-sm text-muted-foreground">{x.label}</p><p className="text-2xl font-bold mt-3 tabular-nums">{money(x.value)}</p></section>)}</div>
 <section className="p-5 bg-card rounded-xl border border-border"><h2 className="font-semibold">Últimos seis meses</h2><p className="text-sm text-muted-foreground mt-1 mb-5">Comisiones registradas, excepto rechazadas. Se aplican los filtros seleccionados.</p><ResponsiveContainer width="100%" height={230}><BarChart data={chart}><CartesianGrid vertical={false} stroke="hsl(var(--border))"/><XAxis dataKey="name" tick={{fill:'hsl(var(--muted-foreground))',fontSize:12}}/><YAxis tick={{fill:'hsl(var(--muted-foreground))',fontSize:12}}/><Tooltip formatter={(v:number)=>money(v)} contentStyle={{background:'hsl(var(--card))',border:'1px solid hsl(var(--border))',borderRadius:12}}/><Bar isAnimationActive={false} dataKey="comisiones" name="Comisiones" fill="hsl(var(--primary))" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></section>
 <section className="rounded-xl bg-card border border-border overflow-hidden"><div className="p-5 border-b border-border"><h2 className="font-semibold">Movimientos · {rows.length}</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/40"><tr>{['Fecha','Origen','Descripción','Estado','Importe'].map(h=><th key={h} className="p-4 text-left font-medium text-muted-foreground">{h}</th>)}</tr></thead><tbody>{rows.slice(current*10,current*10+10).map(c=><tr key={c.id} className="border-t border-border"><td className="p-4 whitespace-nowrap">{new Date(c.created_at).toLocaleDateString('es-PE')}</td><td className="p-4">{TYPE_LABELS[c.type]||c.type}</td><td className="p-4 min-w-48">{c.description||'Sin descripción'}</td><td className="p-4">{STATUS_CONFIG[c.status]?.label||c.status}</td><td className="p-4 font-semibold whitespace-nowrap tabular-nums">{money(Number(c.amount))}</td></tr>)}{!rows.length&&<tr><td colSpan={5} className="p-10 text-center text-muted-foreground">No hay movimientos con estos filtros.</td></tr>}</tbody></table></div><div className="p-4 border-t border-border flex justify-between items-center text-sm"><span>Página {current+1} de {pages}</span><div className="flex gap-3"><button disabled={current===0} onClick={()=>setPage(current-1)} className="disabled:opacity-40">Anterior</button><button disabled={current+1>=pages} onClick={()=>setPage(current+1)} className="disabled:opacity-40">Siguiente</button></div></div></section><MlmPointsSummary/></div>;
}
