import {useEffect,useState} from 'react';
import {supabase} from '@/lib/backend/client';
import {useAuthStore} from '@/store/authStore';
import {toast} from 'sonner';
export function ExistingNetworkRequest({sponsorId,onDone,requirePosition=false}:{sponsorId:string;onDone:()=>void;requirePosition?:boolean}){
 const [position,setPosition]=useState('left');
 const [query,setQuery]=useState(''),[matches,setMatches]=useState<any[]>([]),[member,setMember]=useState<any>(null),[busy,setBusy]=useState(false),[searched,setSearched]=useState(false);
 async function search(){setBusy(true);const r=await supabase.rpc('search_network_member',{p_query:query});setBusy(false);setSearched(true);if(r.error)toast.error(r.error.message);else setMatches(r.data||[]);}
 async function send(){if(!member)return;setBusy(true);const r=await supabase.rpc('request_network_membership',{p_member:member.id,p_sponsor:sponsorId,p_position:position});setBusy(false);if(r.error)toast.error(r.error.code==='23505'?'Este usuario ya tiene una solicitud pendiente.':r.error.message);else{toast.success('Solicitud enviada. El usuario debe aceptarla desde Mi Red.');onDone();}}
 return <div className="space-y-5"><p className="text-sm text-muted-foreground">Busca por el correo completo o el nombre de usuario exacto. La persona recibirá una solicitud dentro del sistema.</p><form className="flex gap-2" onSubmit={e=>{e.preventDefault();search();}}><input aria-label="Correo o usuario" value={query} onChange={e=>{setQuery(e.target.value);setMember(null);setMatches([]);setSearched(false);}} placeholder="Correo o usuario exacto" className="min-w-0 flex-1 rounded-xl border border-border bg-background px-3 py-3 text-sm"/><button disabled={busy||query.trim().length<3} className="rounded-xl border border-border px-4 disabled:opacity-50">Buscar</button></form>{matches.map(m=><button key={m.id} onClick={()=>setMember(m)} className={`w-full text-left p-4 rounded-xl border ${member?.id===m.id?'border-primary':'border-border'}`}><span className="block font-semibold">{m.full_name||m.username}</span><span className="block text-sm text-muted-foreground mt-1">@{m.username} · {m.has_sponsor?'Requiere revisión de traslado':'Sin patrocinador'}</span></button>)}{searched&&!matches.length&&<p className="text-sm text-muted-foreground">No hay coincidencias. Revisa los datos con la persona.</p>}{member&&<p className="text-sm text-muted-foreground">{member.has_sponsor?'Primero debe aceptar el usuario; después, un administrador autorizado revisará el cambio de red.':'La vinculación se realizará cuando el usuario acepte.'}</p>}<fieldset hidden={!requirePosition} className="space-y-2"><legend className="text-sm font-medium mb-2">Posición en la red</legend><div className="flex gap-4">{[["left","Izquierda"],["right","Derecha"]].map(([value,label])=><label key={value} className="flex items-center gap-2"><input type="radio" name="request-position" value={value} checked={position===value} onChange={()=>setPosition(value)}/>{label}</label>)}</div></fieldset><div className="form-actions"><button disabled={!member||busy} onClick={send} className="rounded-xl px-5 py-3 bg-primary text-primary-foreground font-semibold disabled:opacity-50">{busy?'Procesando…':'Enviar solicitud'}</button></div></div>;
}
export default function NetworkRequests({canReview,onChanged}:{canReview:boolean;onChanged:()=>void}){
 const {user}=useAuthStore();const [rows,setRows]=useState<any[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState('');
 async function load(){const r=await supabase.rpc('network_request_list');if(r.error)setError(r.error.message);else{setRows(r.data||[]);setError('');}}
 useEffect(()=>{load();},[user?.id]);
 async function respond(id:string,action:string){setBusy(id);const r=await supabase.rpc('respond_network_request',{p_id:id,p_action:action});setBusy('');if(r.error)toast.error(r.error.message);else{toast.success('Solicitud actualizada');load();onChanged();}}
 const pending=rows.filter(r=>['pending','review'].includes(r.status));
 const labels:Record<string,string>={pending:'Pendiente de aceptación',review:'Traslado por revisar',accepted:'Aceptada',rejected:'Rechazada',cancelled:'Cancelada'};
 return <section className="border border-border rounded-xl overflow-hidden"><button onClick={()=>{setOpen(!open);if(!open)load();}} className="w-full flex justify-between gap-4 text-left p-4 font-medium"><span>Solicitudes de afiliación {pending.length>0&&`(${pending.length})`}</span><span>{open?'−':'+'}</span></button>{open&&<div className="px-4 pb-4 space-y-3">{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{!rows.length&&!error&&<p className="text-sm text-muted-foreground">No tienes solicitudes. Puedes invitar a una persona desde Agregar afiliado.</p>}{rows.map(r=><article key={r.id} className="border-t border-border py-4 space-y-3"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-medium">{r.member_name} → Red de {r.sponsor_name}</p><p className="text-xs text-muted-foreground mt-1">{new Date(r.created_at).toLocaleDateString('es-PE')}</p></div><span className="text-sm text-muted-foreground">{labels[r.status]}</span></div><p className="text-sm text-muted-foreground">{r.previous_sponsor_id?"El traslado conserva los integrantes de la red y necesita la aceptación de la persona y la revisión de un administrador autorizado.":"Al aceptar, la persona se vinculará al patrocinador indicado."}</p><div className="flex flex-wrap justify-end gap-3">{r.status==='pending'&&r.member_id===user?.id&&<><button disabled={busy===r.id} onClick={()=>respond(r.id,'reject')} className="px-3 py-2 border border-border rounded-lg">Rechazar</button><button disabled={busy===r.id} onClick={()=>respond(r.id,'accept')} className="px-3 py-2 bg-primary text-primary-foreground rounded-lg">Aceptar invitación</button></>}{r.status==='review'&&canReview&&<><button disabled={busy===r.id} onClick={()=>respond(r.id,'reject')} className="px-3 py-2 border border-border rounded-lg">Rechazar traslado</button><button disabled={busy===r.id} onClick={()=>respond(r.id,'approve')} className="px-3 py-2 bg-primary text-primary-foreground rounded-lg">Aprobar traslado</button></>}{['pending','review'].includes(r.status)&&r.requester_id===user?.id&&<button disabled={busy===r.id} onClick={()=>respond(r.id,'cancel')} className="px-3 py-2 border border-border rounded-lg">Cancelar solicitud</button>}</div></article>)}</div>}</section>;
}
