import {useEffect,useState} from 'react';
import {supabase} from '@/lib/backend/client';
import {toast} from 'sonner';
export default function RankPointsAdmin(){
 const [search,setSearch]=useState(''),[members,setMembers]=useState<any[]>([]),[member,setMember]=useState<any>(null),[data,setData]=useState<any>(null),[points,setPoints]=useState(''),[reason,setReason]=useState(''),[reference,setReference]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const [request,setRequest]=useState(()=>crypto.randomUUID());
 useEffect(()=>{let alive=true;const timer=setTimeout(async()=>{if(search.trim().length<2){setMembers([]);return;}const {data,error}=await supabase.from('profiles').select('id,full_name,email').ilike('full_name',`%${search.trim().replace(/[%_]/g,'')}%`).limit(10);if(alive){setMembers(data||[]);setError(error?'No se pudieron buscar los usuarios.':'');}},250);return()=>{alive=false;clearTimeout(timer);};},[search]);
 useEffect(()=>{let alive=true;setData(null);if(member)supabase.rpc('rank_points_progress',{p_user:member.id}).then(({data,error})=>{if(alive){setData(data);setError(error?.message||'');}});return()=>{alive=false;};},[member]);
 const input='w-full rounded-xl border border-border bg-background px-3 py-3 text-sm';
 async function save(e:React.FormEvent){e.preventDefault();if(saving||!member)return;setSaving(true);setError('');const {error}=await supabase.rpc('add_rank_points',{p_user:member.id,p_points:Number(points),p_reason:reason,p_reference:reference,p_request:request});if(error){setError(error.code==='23505'?'Esta referencia ya fue registrada para este usuario.':error.message);}else{toast.success('Puntos registrados y rango evaluado');setPoints('');setReason('');setReference('');setRequest(crypto.randomUUID());const result=await supabase.rpc('rank_points_progress',{p_user:member.id});setData(result.data);}setSaving(false);}
 return <section className="border border-border rounded-xl bg-card p-5 space-y-5"><header><h2 className="text-lg font-bold">Puntos por operaciones externas</h2><p className="text-sm text-muted-foreground mt-2">Registra ventas de terrenos u otras operaciones. Las compras pagadas de la tienda suman sus puntos automáticamente. Los puntos no representan dinero.</p></header><label className="block space-y-2"><span className="text-sm block">Buscar usuario por nombre</span><input className={input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Escribe al menos 2 letras"/></label>{members.length>0&&<ul className="max-h-60 overflow-auto border border-border rounded-xl">{members.map(m=><li key={m.id}><button type="button" className="w-full text-left px-4 py-3 hover:bg-muted border-b border-border last:border-0" onClick={()=>{setMember(m);setSearch('');setMembers([]);setRequest(crypto.randomUUID());}}><span className="block font-medium">{m.full_name}</span><span className="text-xs text-muted-foreground">{m.email}</span></button></li>)}</ul>}{search.length>=2&&members.length===0&&<p className="text-sm text-muted-foreground">No hay coincidencias disponibles.</p>}
 {member&&<><div className="border-y border-border py-4 flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{member.full_name}</p><p className="text-sm text-muted-foreground">{member.email}</p></div><div><p className="text-sm text-muted-foreground">Puntos para rango</p><strong className="text-xl">{data?Number(data.volume).toLocaleString('es-PE'):'—'}</strong></div></div><form onSubmit={save} className="space-y-5"><div className="grid sm:grid-cols-2 gap-5"><label className="block space-y-2 text-sm"><span className="block">Puntos a registrar</span><input required type="number" step="0.01" className={input} value={points} onChange={e=>setPoints(e.target.value)}/><span className="block text-xs text-muted-foreground">Usa un valor negativo para corregir un registro.</span></label><label className="block space-y-2 text-sm"><span className="block">Referencia de la operación</span><input required minLength={3} maxLength={100} className={input} value={reference} onChange={e=>setReference(e.target.value)} placeholder="Contrato, venta o corrección"/></label></div><label className="block space-y-2 text-sm"><span className="block">Motivo y detalle</span><textarea required minLength={5} maxLength={1000} rows={3} className={input} value={reason} onChange={e=>setReason(e.target.value)}/></label><p className="text-xs text-muted-foreground">El registro conserva tu identidad y fecha. El rango sube automáticamente al cumplir los requisitos; una corrección no elimina reconocimientos ya obtenidos.</p><div className="form-actions"><button disabled={saving||!Number(points)||!data} className="bg-primary text-primary-foreground rounded-xl px-5 py-3 font-semibold disabled:opacity-50">{saving?'Guardando…':'Guardar puntos'}</button></div></form><div><h3 className="font-semibold mb-3">Últimos 30 movimientos</h3>{data?.history?.length?data.history.map((h:any,i:number)=><div key={i} className="py-3 border-b border-border flex justify-between gap-4 text-sm"><div className="min-w-0"><p className="font-medium">{h.source}{h.reversed?' · Revertido':''}</p><p className="text-muted-foreground break-words">{h.description}</p><p className="text-xs text-muted-foreground mt-1">{new Date(h.created_at).toLocaleString('es-PE')}</p></div><strong className="shrink-0">{h.points>0?'+':''}{h.points}</strong></div>):<p className="text-sm text-muted-foreground">Sin movimientos registrados.</p>}</div></>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}</section>;
}
