import {useEffect,useState} from 'react';
import {supabase} from '@/lib/backend/client';
import {useAuthStore} from '@/store/authStore';
import {Link} from '@/lib/router';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Download,ArrowRight,RefreshCw,ShoppingBag,Users,Wallet,Clock} from 'lucide-react';
import {BarChart,Bar,AreaChart,Area,LineChart,Line,PieChart,Pie,Cell,ResponsiveContainer,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';

type Summary={permissions:Record<string,boolean>;scope:Record<string,string>;orders:{count:number;pending:number;paid:number};people:{count:number;active:number};money:{currency:string;sales:number;earned:number;pending:number}[];monthly:{month:string;currency:string;sales:number;earned:number;orders:number}[];registrations:{month:string;count:number}[]};
const money=(n:number,c:string)=>new Intl.NumberFormat('es-PE',{style:'currency',currency:c}).format(n);
const monthName=(s:string)=>new Date(s+'-02T12:00:00').toLocaleDateString('es-PE',{month:'short',year:'2-digit'});
const card='min-w-0 rounded-xl border border-border bg-card p-5 sm:p-6';
const button='inline-flex min-h-10 items-center justify-center gap-2 rounded-lg border border-border px-4 py-2 text-sm hover:bg-muted';
export default function AccountOverview({report=false}:{report?:boolean}){
 const {user}=useAuthStore();const [period,setPeriod]=useState('6');const [currency,setCurrency]=useState('PEN');const [summary,setSummary]=useState<Summary|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [retry,setRetry]=useState(0);const [loadedUser,setLoadedUser]=useState<string|null>(null);
 useEffect(()=>{let alive=true;setLoading(true);setError('');if(!user?.id)return()=>{alive=false;};
 const now=new Date();const start=new Date(now.getFullYear(),now.getMonth()-Number(period)+1,1);
 Promise.resolve(supabase.rpc('account_analytics',{p_from:start.toISOString(),p_to:now.toISOString(),p_report:report})).then(({data,error})=>{if(!alive)return;if(error)setError(error.code==='42501'?'Tu cargo no tiene permiso para ver esta sección.':'No pudimos cargar los datos. Inténtalo nuevamente.');else{setSummary(data as Summary);setLoadedUser(user.id);setCurrency(data.money?.[0]?.currency||'PEN');}setLoading(false);}).catch(()=>{if(alive){setError('No pudimos conectar. Inténtalo nuevamente.');setLoading(false);}});return()=>{alive=false;};
 },[user?.id,report,period,retry]);
 const ready=loadedUser===user?.id&&!!summary;
 const p=summary?.permissions||{};const global=summary?.scope.orders==='global';const peopleGlobal=summary?.scope.people==='global';const commissionGlobal=summary?.scope.commissions==='global';const canPeople=p.view_users||p.view_network;const canCommission=p.view_commissions||p.approve_commissions;
 const totals=summary?.money.find(m=>m.currency===currency)||{sales:0,earned:0,pending:0};
 const months=Array.from({length:Number(period)},(_,i)=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-Number(period)+1+i);const key=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');return {month:key,name:monthName(key),sales:0,earned:0,orders:0,...summary?.monthly.find(m=>m.month===key&&m.currency===currency),people:summary?.registrations.find(m=>m.month===key)?.count||0};});
 const exportReport=()=>{if(!summary||!p.export_data)return;const rows=[['Mes','Moneda',global?'Ventas pagadas':'Compras pagadas',...(canCommission?['Comisiones aprobadas y pagadas']:[]),'Pedidos',...(canPeople?[peopleGlobal?'Registros':'Referidos directos']:[])],...months.map(m=>[m.month,currency,m.sales,...(canCommission?[m.earned]:[]),m.orders,...(canPeople?[m.people]:[])])];const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`reporte-${currency}-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const links=[{show:global,to:'/dashboard/admin/pedidos',label:'Gestionar pedidos'},{show:peopleGlobal,to:'/dashboard/usuarios',label:'Consultar usuarios'},{show:canCommission,to:'/dashboard/comisiones',label:commissionGlobal?'Revisar comisiones':'Mis comisiones'},{show:p.view_network,to:'/dashboard/red',label:'Mi red'},{show:!global,to:'/dashboard/pedidos',label:'Mis pedidos'},{show:true,to:'/dashboard/configuracion',label:'Mis preferencias'}].filter(l=>l.show);
 if(!ready&&!error)return <div className="min-h-[60vh]" role="status" aria-busy="true"><span className="sr-only">Cargando tu dashboard…</span></div>;
 if(!ready&&error)return <div className={card} role="alert"><h1 className="text-xl font-semibold">{report?'Reportes':'Dashboard'}</h1><p className="my-4">{error}</p><button className={button} onClick={()=>setRetry(r=>r+1)}>Reintentar</button></div>;
 return <div className="space-y-6 max-w-7xl"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">{report?'Reportes':global?'Resumen del negocio':peopleGlobal?'Panel de operaciones':`Hola, ${user?.full_name?.split(' ')[0]||'bienvenido'}`}</h1><p className="mt-2 text-sm text-muted-foreground">{report?'Resultados del período según los permisos de tu cargo.':global?'Ventas, usuarios y comisiones para gestionar el negocio.':peopleGlobal?'Actividad de usuarios y accesos a las tareas de tu cargo.':canCommission||canPeople?'Tus compras y actividad de la red según tus permisos.':'Consulta tus compras y pedidos.'}</p></div><div className="flex flex-wrap gap-2"><Select value={period} onValueChange={setPeriod} disabled={loading}><SelectTrigger aria-label="Período del reporte" className="w-44"><SelectValue/></SelectTrigger><SelectContent>{[1,3,6,12].map(n=><SelectItem key={n} value={String(n)}>{n===1?'Este mes':`Últimos ${n} meses`}</SelectItem>)}</SelectContent></Select>{summary&&summary.money.length>1&&<Select value={currency} onValueChange={setCurrency}><SelectTrigger aria-label="Moneda del reporte" className="w-28"><SelectValue/></SelectTrigger><SelectContent>{summary.money.map(m=><SelectItem key={m.currency} value={m.currency}>{m.currency}</SelectItem>)}</SelectContent></Select>}{report&&p.export_data&&<button className={button} disabled={loading} onClick={exportReport}><Download size={16}/>Exportar CSV</button>}</div></header>
 {error?<div role="alert" className="py-12 space-y-4"><p>{error}</p><button className={button} onClick={()=>setRetry(r=>r+1)}><RefreshCw size={16}/>Volver a intentar</button></div>:summary&&<div aria-busy={loading} className="space-y-6">{loading&&<p role="status" className="sr-only">Actualizando el período…</p>}
 <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">
 <Metric Icon={Wallet} label={global?'Ventas pagadas':'Mis compras pagadas'} value={money(totals.sales,currency)} detail={`${summary.orders.paid} pedidos pagados · todas las monedas`}/>
 <Metric Icon={ShoppingBag} label={global?'Pedidos por cobrar':'Mis pedidos pendientes'} value={String(summary.orders.pending)} detail={`${summary.orders.count} pedidos en el período`}/>
 {canPeople&&<Metric Icon={Users} label={peopleGlobal?'Usuarios registrados':'Mis nuevos referidos'} value={String(summary.people.count)} detail={`${summary.people.active} activos · ${peopleGlobal?'todo el sistema':'red directa'}`}/>}
 {canCommission&&<Metric Icon={Wallet} label={commissionGlobal?'Comisiones aprobadas':'Mis comisiones aprobadas'} value={money(totals.earned,currency)} detail={`${money(totals.pending,currency)} pendientes de aprobación`}/>}
 </div>
 {!report&&<section className={card}><div className="flex items-center gap-2 mb-5"><Clock size={18} className="text-primary"/><h2 className="font-semibold">{global?'Atención y seguimiento':'Tu actividad pendiente'}</h2></div><div className="grid sm:grid-cols-2 gap-5"><Link to={global?'/dashboard/admin/pedidos':'/dashboard/pedidos'} className="flex items-center justify-between gap-4 rounded-lg border border-border p-4 hover:bg-muted"><span><span className="block font-medium">{summary.orders.pending} pedidos pendientes de pago</span><span className="mt-1 block text-sm text-muted-foreground">{global?'Consulta los pedidos y revisa su estado.':'Retoma tus pedidos desde el historial.'}</span></span><ArrowRight size={18} className="shrink-0 text-primary"/></Link>{canCommission&&<Link to="/dashboard/comisiones" className="flex items-center justify-between gap-4 rounded-lg border border-border p-4 hover:bg-muted"><span><span className="block font-medium">{money(totals.pending,currency)} por aprobar</span><span className="mt-1 block text-sm text-muted-foreground">{commissionGlobal?'Comisiones del negocio pendientes de aprobación.':'Consulta el estado de tus comisiones pendientes.'}</span></span><ArrowRight size={18} className="shrink-0 text-primary"/></Link>}</div><nav className="mt-5 flex flex-wrap gap-3 border-t border-border pt-5" aria-label="Accesos de tu cargo">{links.map(l=><Link key={l.to} to={l.to} className={button}>{l.label}<ArrowRight size={15}/></Link>)}</nav></section>}
 <div className="grid xl:grid-cols-3 gap-5">
 <section className={`${card} xl:col-span-2 space-y-4`}><h2 className="font-semibold">{global?'Evolución de ventas':'Evolución de mis compras'} · {currency}</h2><p className="text-sm text-muted-foreground">Importes pagados; excluye pedidos cancelados o reembolsados.</p><Chart data={months} field="sales" label={global?'Ventas':'Compras'} currency={currency} variant="area"/></section>
 <section className={`${card} space-y-4`}><h2 className="font-semibold">Estado de los pagos</h2><p className="text-sm text-muted-foreground">{summary.orders.count} pedidos · todas las monedas</p><PaymentDistribution orders={summary.orders}/></section>
 </div>
 <div className="grid lg:grid-cols-2 gap-5"><section className={`${card} space-y-4`}><h2 className="font-semibold">Pedidos por mes · {currency}</h2><p className="text-sm text-muted-foreground">Cantidad de pedidos registrados, en cualquier estado.</p><Chart data={months} field="orders" label="Pedidos"/></section>
 {canCommission&&<section className={`${card} space-y-4`}><h2 className="font-semibold">{commissionGlobal?'Comisiones del negocio':'Mis comisiones'} · {currency}</h2><p className="text-sm text-muted-foreground">Evolución de las comisiones aprobadas y pagadas.</p><Chart data={months} field="earned" label="Comisiones" currency={currency} variant="line"/></section>}
 {canPeople&&<><section className={`${card} space-y-4`}><h2 className="font-semibold">{peopleGlobal?'Nuevos usuarios':'Nuevos referidos directos'}</h2><p className="text-sm text-muted-foreground">Registros realizados durante el período seleccionado.</p><Chart data={months} field="people" label="Personas"/></section><section className={`${card} space-y-5`}><h2 className="font-semibold">{peopleGlobal?'Actividad de las cuentas':'Actividad de mis referidos'}</h2><p className="text-sm text-muted-foreground">Estado actual de las personas registradas en el período.</p><div className="flex items-baseline gap-3"><span className="text-4xl font-semibold tabular-nums">{summary.people.active}</span><span className="text-sm text-muted-foreground">de {summary.people.count} con estado activo</span></div><div className="h-3 overflow-hidden rounded-full bg-muted" role="meter" aria-label="Cuentas activas" aria-valuemin={0} aria-valuemax={summary.people.count||1} aria-valuenow={summary.people.active}><div className="h-full bg-primary" style={{width:`${summary.people.count?summary.people.active/summary.people.count*100:0}%`}}/></div><dl className="divide-y divide-border text-sm"><div className="flex justify-between gap-4 py-4"><dt>Activas</dt><dd className="font-medium tabular-nums">{summary.people.active}</dd></div><div className="flex justify-between gap-4 py-4"><dt>Otros estados</dt><dd className="font-medium tabular-nums">{summary.people.count-summary.people.active}</dd></div></dl><Link to={peopleGlobal?'/dashboard/usuarios':'/dashboard/red'} className={button}>{peopleGlobal?'Consultar usuarios':'Ver mi red'}<ArrowRight size={16}/></Link></section></>}
 </div>
 {<section className={card}><h2 className="font-semibold mb-4">Detalle mensual · {currency}</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-border text-muted-foreground"><th className="py-3 pr-6 text-left">Mes</th><th className="p-3 text-right">{global?'Ventas':'Compras'} pagadas</th>{canCommission&&<th className="p-3 text-right">Comisiones aprobadas</th>}<th className="p-3 text-right">Pedidos</th>{canPeople&&<th className="py-3 pl-6 text-right">{peopleGlobal?'Usuarios nuevos':'Referidos nuevos'}</th>}</tr></thead><tbody>{months.map(m=><tr key={m.month} className="border-b border-border"><td className="py-4 pr-6 whitespace-nowrap">{m.name}</td><td className="p-3 text-right whitespace-nowrap tabular-nums">{money(m.sales,currency)}</td>{canCommission&&<td className="p-3 text-right whitespace-nowrap tabular-nums">{money(m.earned,currency)}</td>}<td className="p-3 text-right">{m.orders}</td>{canPeople&&<td className="py-4 pl-6 text-right">{m.people}</td>}</tr>)}</tbody></table></div><p className="mt-4 text-xs text-muted-foreground">Comisiones aprobadas incluye las ya pagadas. Los importes se muestran en su moneda original. Los usuarios nuevos no dependen de la moneda.</p></section>}
 </div>}
 </div>;
}
function Metric({label,value,detail,Icon}:{label:string;value:string;detail:string;Icon:typeof Wallet}){return <div className={`${card} space-y-3`}><div className="flex items-center justify-between gap-3"><h2 className="text-sm text-muted-foreground">{label}</h2><Icon size={18} className="shrink-0 text-primary"/></div><p className="text-2xl font-semibold tabular-nums break-words">{value}</p><p className="text-xs text-muted-foreground leading-relaxed">{detail}</p></div>;}
const tooltipStyle={background:'hsl(var(--popover))',border:'1px solid hsl(var(--border))',borderRadius:8,color:'hsl(var(--foreground))'};
function Chart({data,field,label,currency,variant='bar'}:{data:any[];field:string;label:string;currency?:string;variant?:'bar'|'area'|'line'}){
 if(!data.some(d=>d[field]>0))return <div className="flex h-[250px] items-center justify-center text-sm text-muted-foreground">Sin movimientos en este período.</div>;
 const axes=<><CartesianGrid vertical={false} stroke="hsl(var(--border))"/><XAxis dataKey="name" tick={{fill:'hsl(var(--muted-foreground))',fontSize:12}} axisLine={false} tickLine={false}/><YAxis allowDecimals={!!currency} tick={{fill:'hsl(var(--muted-foreground))',fontSize:12}} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={(v:number)=>[currency?money(v,currency):v,label]}/></>;
 return <ResponsiveContainer width="100%" height={250}>{variant==='area'?<AreaChart data={data}>{axes}<Area type="monotone" dataKey={field} name={label} stroke="hsl(var(--primary))" strokeWidth={2} fill="hsl(var(--primary))" fillOpacity={0.12} isAnimationActive={false}/></AreaChart>:variant==='line'?<LineChart data={data}>{axes}<Line type="monotone" dataKey={field} name={label} stroke="hsl(var(--primary))" strokeWidth={2} dot={{r:4}} isAnimationActive={false}/></LineChart>:<BarChart data={data}>{axes}<Bar dataKey={field} name={label} fill="hsl(var(--primary))" maxBarSize={48} radius={[4,4,0,0]} isAnimationActive={false}/></BarChart>}</ResponsiveContainer>;
}
function PaymentDistribution({orders}:{orders:Summary['orders']}){
 const data=[{name:'Pagados',value:orders.paid,color:'hsl(var(--primary))'},{name:'Pendientes',value:orders.pending,color:'hsl(var(--muted-foreground))'},{name:'Otros estados',value:Math.max(0,orders.count-orders.paid-orders.pending),color:'hsl(var(--border))'}];
 return <>{orders.count?<ResponsiveContainer width="100%" height={175}><PieChart><Pie data={data.filter(x=>x.value)} dataKey="value" nameKey="name" innerRadius={48} outerRadius={73} stroke="hsl(var(--card))" strokeWidth={4} isAnimationActive={false}>{data.filter(x=>x.value).map(d=><Cell key={d.name} fill={d.color}/>)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={(v:number)=>[v,'Pedidos']}/></PieChart></ResponsiveContainer>:<div className="h-[175px] flex items-center justify-center text-sm text-muted-foreground">Sin pedidos en este período.</div>}<dl className="space-y-3">{data.map(d=><div key={d.name} className="flex items-center justify-between gap-4 text-sm"><dt className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{background:d.color}}/>{d.name}</dt><dd className="font-medium tabular-nums">{d.value}</dd></div>)}</dl></>;
}
