import { useEffect, useState } from 'react';
import { useDatabase } from '@/lib/backend';
import { supabase } from '@/lib/backend/client';
import { useConfig } from '@/store/configStore';
import { toast } from 'sonner';

const labels:Record<string,string>={client_id:'Client ID',client_secret:'Client Secret',access_token:'Access Token de producción',phone_number:'Número de celular',merchant_name:'Titular'};
const fields:Record<string,string[]>={paypal:['client_id','client_secret'],mercadopago:['access_token'],yape:['phone_number','merchant_name'],plin:['phone_number','merchant_name']};
export default function PaymentsManager(){
 const db=useDatabase();const {refresh}=useConfig();const [gateways,setGateways]=useState<any[]>([]);const [payments,setPayments]=useState<any[]>([]);const [key,setKey]=useState('');const [rate,setRate]=useState('');const [busy,setBusy]=useState('');const [checks,setChecks]=useState<Record<string,string>>({});
 const input='w-full p-3 rounded-lg border border-border bg-background text-foreground text-sm';
 const button='px-4 py-2 rounded-lg bg-primary text-white text-sm disabled:opacity-50';
 const load=async()=>{const [g,p,c]=await Promise.all([db.select('payment_gateways'),db.select('payment_sessions',{filter:{status:'review'},order:{column:'created_at',ascending:false},limit:50}),db.select<any>('system_config',{filter:{key:['fixer_api_key','exchange_rate_usd']}})]);if(g.error||p.error||c.error){toast.error('No se pudo cargar toda la configuración.');return}setGateways((g.data as any[]||[]).filter(g=>['paypal','mercadopago','yape','plin','transfer'].includes(g.slug)));setPayments(p.data as any[]||[]);for(const r of c.data as any[]||[]){if(r.key==='fixer_api_key')setKey(r.value||'');if(r.key==='exchange_rate_usd')setRate(r.value||'')}};
 useEffect(()=>{load()},[]);
 const change=(id:string,values:any)=>setGateways(p=>p.map(g=>g.id===id?{...g,...values}:g));
 const save=async(g:any)=>{setBusy(g.id);try{if(g.is_active){if(g.slug==='transfer'){const a=JSON.parse(g.credentials.accounts||'[]');if(!a.length||a.some((v:any)=>!v.bank?.trim()||!v.holder?.trim()||!v.number?.trim()))throw new Error('Completa banco, titular y cuenta antes de mostrar este método.')}else if(fields[g.slug].some(f=>!g.credentials[f]?.trim()))throw new Error('Completa los campos antes de mostrar este método.');}const {error}=await db.update('payment_gateways',g.id,{credentials:g.credentials,is_active:g.is_active,test_mode:false,updated_at:new Date().toISOString()});if(error)throw new Error('No se pudo guardar.');toast.success('Método guardado.')}catch(e:any){toast.error(e.message)}finally{setBusy('')}};
 const currency=async(update:boolean)=>{setBusy('currency');try{if(!(Number(rate)>0))throw new Error('Ingresa una tasa válida.');const {error}=await db.upsert('system_config',[{key:'fixer_api_key',value:key.trim(),category:'currency',is_sensitive:true},{key:'exchange_rate_usd',value:rate,category:'currency',is_sensitive:false}],'key');if(error)throw new Error('No se pudo guardar la configuración.');if(update){const {data,error}=await db.invoke<any>('exchange-rate');if(error||!data?.success)throw new Error(data?.error||'No se pudo conectar con Fixer.');setRate(String(data.rate));setChecks(p=>({...p,currency:`Tasa actualizada: 1 USD = ${data.rate} PEN`}))}else toast.success('Tipo de cambio guardado.');await refresh()}catch(e:any){setChecks(p=>({...p,currency:e.message}))}finally{setBusy('')}};
 const checkGateway=async(slug:string)=>{setBusy(slug);const {data,error}=await db.invoke<any>('process-payment',{body:{action:'check_gateway',gateway:slug}});setChecks(p=>({...p,[slug]:error||!data?.success?(data?.error||'No se pudo verificar.'):data.message}));setBusy('')};
 const receipt=async(path:string)=>{const {data,error}=await supabase.storage.from('payment-receipts').createSignedUrl(path,120);if(error)toast.error('No se pudo abrir el comprobante.');else window.open(data.signedUrl,'_blank','noopener,noreferrer')};
 const review=async(id:string,approve:boolean)=>{setBusy(id);const {data,error}=await db.invoke<any>('process-payment',{body:{action:'review',session_id:id,approve}});if(error||!data?.success)toast.error(data?.error||'No se pudo revisar el pago.');else{toast.success(approve?'Pago confirmado.':'Comprobante rechazado.');setPayments(p=>p.filter(x=>x.id!==id))}setBusy('')};
 return <div className="space-y-8 max-w-4xl"><div><h2 className="text-xl font-semibold">Métodos de pago</h2><p className="text-sm text-muted-foreground mt-1">PayPal y Mercado Pago cobran en su checkout. Yape, Plin y transferencias requieren revisión del comprobante.</p></div>
 <section className="space-y-4"><h3 className="font-semibold">Tipo de cambio · Fixer</h3><div className="grid sm:grid-cols-2 gap-4"><label className="text-sm">1 USD equivale a (PEN)<input className={input+' mt-2'} type="number" min="0.0001" step="0.0001" value={rate} onChange={e=>setRate(e.target.value)}/></label><label className="text-sm">API key<input className={input+' mt-2'} type="password" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)}/></label></div><div className="flex gap-3 flex-wrap"><button className={button} disabled={busy==='currency'} onClick={()=>currency(true)}>Guardar y actualizar desde Fixer</button><button className="text-sm px-3 py-2 border border-border rounded-lg" disabled={busy==='currency'} onClick={()=>currency(false)}>Guardar tasa manual</button></div>{checks.currency&&<p role="status" className="text-sm text-muted-foreground">{checks.currency}</p>}</section>
 {gateways.map(g=>{let accounts:any[]=[];try{accounts=JSON.parse(g.credentials.accounts||'[]')}catch{}const setAccounts=(a:any[])=>change(g.id,{credentials:{...g.credentials,accounts:JSON.stringify(a)}});return <section key={g.id} className="space-y-4 border-t border-border/50 pt-6"><div className="flex items-center justify-between gap-4"><h3 className="font-semibold">{g.name}{g.slug==='transfer'&&<span className="font-normal text-sm text-muted-foreground"> · Opcional</span>}</h3><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={g.is_active} onChange={e=>change(g.id,{is_active:e.target.checked})}/>Mostrar al pagar</label></div>{g.slug==='transfer'?<div className="space-y-5">{accounts.map((a,i)=><div key={i} className="grid sm:grid-cols-2 gap-3"><label className="text-sm">Banco<input list="banks" className={input} value={a.bank} onChange={e=>setAccounts(accounts.map((x,n)=>n===i?{...x,bank:e.target.value}:x))}/></label>{[['holder','Titular'],['number','Número de cuenta'],['cci','CCI (opcional)']].map(([k,l])=><label key={k} className="text-sm">{l}<input className={input} value={a[k]||''} onChange={e=>setAccounts(accounts.map((x,n)=>n===i?{...x,[k]:e.target.value}:x))}/></label>)}<button onClick={()=>setAccounts(accounts.filter((_,n)=>n!==i))} className="text-sm text-muted-foreground text-left">Quitar cuenta</button></div>)}<datalist id="banks">{['BCP','Interbank','BBVA','Scotiabank','Banco de la Nación','BanBif','Banco Pichincha'].map(b=><option key={b} value={b}/>)}</datalist><button className="text-primary text-sm" onClick={()=>setAccounts([...accounts,{bank:'',holder:'',number:'',cci:'',currency:'PEN'}])}>+ Añadir cuenta bancaria</button><p className="text-xs text-muted-foreground">Cuentas en soles. Puedes indicar otro banco escribiendo su nombre.</p></div>:<div className="grid sm:grid-cols-2 gap-4">{fields[g.slug].map(f=><label key={f} className="text-sm">{labels[f]}<input className={input+' mt-2'} type={/secret|token/.test(f)?'password':'text'} autoComplete="off" value={g.credentials[f]||''} onChange={e=>change(g.id,{credentials:{...g.credentials,[f]:e.target.value}})}/></label>)}</div>}<div className="flex gap-4"><button className={button} disabled={busy===g.id} onClick={()=>save(g)}>Guardar {g.name}</button>{['paypal','mercadopago'].includes(g.slug)&&<button className="text-sm text-primary" disabled={busy===g.slug} onClick={()=>checkGateway(g.slug)}>Verificar conexión de {g.name}</button>}</div>{checks[g.slug]&&<p role="status" className="text-sm text-muted-foreground">{checks[g.slug]}</p>}</section>})}
 <section className="space-y-4 border-t border-border/50 pt-6"><h3 className="font-semibold">Comprobantes pendientes</h3>{!payments.length?<p className="text-sm text-muted-foreground">No hay comprobantes pendientes de revisión.</p>:payments.map(p=><div key={p.id} className="py-3 space-y-2"><p className="text-sm font-medium">{p.currency} {p.amount} · {p.gateway} · {p.order_id?'Compra':'Membresía '+p.plan_slug}</p><p className="text-xs text-muted-foreground">Operación: {p.operation_reference}</p><div className="flex gap-4 flex-wrap text-sm"><button onClick={()=>receipt(p.receipt_path)} className="text-primary">Ver comprobante</button><button disabled={busy===p.id} onClick={()=>review(p.id,true)}>Confirmar pago</button><button disabled={busy===p.id} onClick={()=>review(p.id,false)} className="text-muted-foreground">Rechazar</button></div></div>)}</section></div>
}
