import { useEffect, useState } from 'react';
import { supabase } from '@/lib/backend/client';
import { useDatabase } from '@/lib/backend';
import { toast } from 'sonner';

export function PaymentReviews({onReviewed}:{onReviewed:()=>void}) {
 const db=useDatabase();const [rows,setRows]=useState<any[]>([]);const [page,setPage]=useState(0);const [more,setMore]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');
 const load=async()=>{const {data,error}=await supabase.from('payment_sessions').select('id,order_id,plan_slug,amount,currency,gateway,operation_reference,receipt_path,created_at').eq('status','review').order('created_at').order('id').range(page*20,page*20+20);if(error){setError('No pudimos cargar los comprobantes.');return;}setError('');setRows((data||[]).slice(0,20));setMore((data||[]).length>20);};
 useEffect(()=>{void load()},[page]);
 const review=async(id:string,approve:boolean)=>{setBusy(id);try{const {data,error}=await db.invoke<any>('process-payment',{body:{action:'review',session_id:id,approve}});if(error||!data?.success)throw new Error(data?.error||'No se pudo revisar el pago.');toast.success(approve?'Pago confirmado.':'Comprobante rechazado.');await load();onReviewed();}catch(e:any){toast.error(e.message)}finally{setBusy('')}};
 const open=async(path:string)=>{const {data,error}=await supabase.storage.from('payment-receipts').createSignedUrl(path,120);if(error)toast.error('No se pudo abrir el comprobante.');else window.open(data.signedUrl,'_blank','noopener,noreferrer')};
 return <section className="bg-card border border-border rounded-xl p-5 space-y-4"><div><h2 className="font-semibold">Comprobantes pendientes</h2><p className="text-sm text-muted-foreground">Revisa transferencias de compras y membresías antes de confirmar el pago.</p></div>{error?<p role="alert">{error} <button onClick={load} className="text-primary">Reintentar</button></p>:!rows.length?<p className="text-sm text-muted-foreground">No hay comprobantes en esta página.</p>:rows.map(row=><article key={row.id} className="border-t border-border pt-4 space-y-3"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-medium">{row.order_id?'Compra':'Membresía · '+row.plan_slug} · {row.gateway}</p><p className="text-sm text-muted-foreground">Operación: {row.operation_reference} · {new Date(row.created_at).toLocaleDateString('es-PE')}</p></div><strong>{row.currency} {Number(row.amount).toFixed(2)}</strong></div><div className="flex flex-wrap justify-end gap-4 text-sm"><button className="text-primary" onClick={()=>open(row.receipt_path)}>Ver comprobante</button><button disabled={!!busy} onClick={()=>review(row.id,false)}>Rechazar</button><button disabled={!!busy} className="rounded-lg bg-primary text-white px-4 py-2 disabled:opacity-50" onClick={()=>review(row.id,true)}>{busy===row.id?'Procesando…':'Confirmar pago'}</button></div></article>)}{(page>0||more)&&<div className="flex justify-end gap-4 text-sm"><button disabled={!page} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page+1}</span><button disabled={!more} onClick={()=>setPage(page+1)}>Siguiente</button></div>}</section>;
}
