import {useEffect,useState} from 'react';
import {supabase} from '@/lib/backend/client';
import {useAuthStore} from '@/store/authStore';
import {Link} from '@/lib/router';
import {toast} from 'sonner';
export default function NotificationInbox(){
 const {user}=useAuthStore();const [items,setItems]=useState<any[]>([]);const [count,setCount]=useState(0);const [unread,setUnread]=useState(false);const [page,setPage]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [version,setVersion]=useState(0);const [busy,setBusy]=useState(false);
 useEffect(()=>{if(!user?.id)return;let live=true;setLoading(true);setError(false);let q=supabase.from('notifications').select('id,title,message,read,created_at,link',{count:'exact'}).eq('user_id',user.id);if(unread)q=q.eq('read',false);Promise.resolve(q.order('created_at',{ascending:false}).range(page*6,page*6+5)).then(r=>{if(live){setError(!!r.error);setItems(r.data||[]);setCount(r.count||0);setLoading(false);}}).catch(()=>{if(live){setError(true);setLoading(false);}});return()=>{live=false;};},[user?.id,unread,page,version]);
 const mark=async(id?:string)=>{if(!user||busy)return;setBusy(true);try{const r=id?await supabase.rpc('mark_notification_read',{p_notification_id:id}):await supabase.rpc('mark_all_notifications_read',{p_user_id:user.id});if(r.error)throw r.error;setVersion(n=>n+1);setPage(0);toast.success(id?'Aviso marcado como leído':'Avisos marcados como leídos');}catch{toast.error('No se pudo actualizar. Inténtalo nuevamente.');}finally{setBusy(false);}};
 return <section className="rounded-xl border border-border bg-card p-5 sm:p-6"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-lg font-semibold">Centro de notificaciones</h2><p className="mt-2 text-sm text-muted-foreground">Consulta tus avisos y gestiona los que quedan por leer.</p></div><button disabled={busy||loading||!items.some(n=>!n.read)} onClick={()=>mark()} className="text-sm text-primary disabled:opacity-50">Marcar todas como leídas</button></div><div className="flex gap-4 mt-5 border-b border-border">{[[false,'Todas'],[true,'Sin leer']].map(([value,label])=><button key={String(value)} onClick={()=>{setUnread(value as boolean);setPage(0);}} className={`pb-3 border-b-2 text-sm ${unread===value?'border-primary text-primary':'border-transparent text-muted-foreground'}`}>{label}</button>)}</div><div aria-busy={loading} className="min-h-24 divide-y divide-border">{error?<p role="alert" className="py-5">No pudimos cargar los avisos. <button className="text-primary" onClick={()=>setVersion(v=>v+1)}>Reintentar</button></p>:items.map(n=><article key={n.id} className="py-5 space-y-2"><div className="flex flex-wrap justify-between gap-2"><h3 className={n.read?'font-medium':'font-semibold'}>{n.title}{!n.read&&<span className="ml-2 text-xs text-primary">Nuevo</span>}</h3><time className="text-xs text-muted-foreground">{new Date(n.created_at).toLocaleString('es-PE',{dateStyle:'medium',timeStyle:'short'})}</time></div><p className="text-sm text-muted-foreground">{n.message}</p><div className="flex gap-4 text-sm">{n.link?.startsWith('/')&&!n.link.startsWith('//')&&<Link to={n.link} className="text-primary">Ver detalle</Link>}{!n.read&&<button disabled={busy} onClick={()=>mark(n.id)} className="text-primary">Marcar como leído</button>}</div></article>)}{!loading&&!error&&!items.length&&<p className="py-8 text-sm text-muted-foreground">{unread?'No tienes avisos pendientes de leer.':'Todavía no hay notificaciones.'}</p>}</div>{count>6&&<footer className="flex justify-end gap-4 items-center pt-4 text-sm"><button disabled={page===0||loading} onClick={()=>setPage(n=>n-1)}>Anterior</button><span>{page+1} / {Math.ceil(count/6)}</span><button disabled={(page+1)*6>=count||loading} onClick={()=>setPage(n=>n+1)}>Siguiente</button></footer>}</section>;
}
